[package]
name = "sdbtree"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
embedded-io = { git = "https://github.com/euugenechou/embedded-io.git" }
serde = { version = "1.0.189", features = ["derive"] }
storage = { version = "0.1.0", path = "storage", features = ["dir"] }
thiserror = "1.0.49"
